reco/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "reco"

urlpatterns = [

    path('', views.mainpage, name='mainpage'),
    path('result/', views.result, name='result'),
    path("detail/<int:recipe_id>", views.detail, name = "detail"),

]

reco_recipe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reco.urls')),
]

reco/models.py
from django.db import models

# Create your models here.
class Recipe_info(models.Model):

    recipe_id = models.IntegerField(default=0, unique=True, primary_key=True)
    type = models.CharField(max_length = 50, default = '')
    titles = models.CharField(max_length = 200, default = '') # recipe_name, title
    comment = models.TextField(default = '')
    images = models.CharField(max_length = 200, default = '') # recipe_main_image_url
    serves = models.CharField(max_length = 50, default = '') # food serves
    cooking = models.CharField(max_length = 50, default = '') # cooking time
    recipes = models.TextField(default = '')
    ingredients = models.TextField(default = '')


class Recipe_token(models.Model):

    recipe = models.ForeignKey('Recipe_info', on_delete=models.CASCADE)
    clean_words = models.TextField()

reco/forms.py
from django import forms

class IngredientInputForm(forms.Form):
    Ingredient_1 = forms.CharField(max_length=10)
    # Ingredient_2 = forms.CharField(max_length=10)
    # Ingredient_3 = forms.CharField(max_length=10)

reco/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from reco.forms import IngredientInputForm
from reco.models import *
from reco.cos_sim import recommend


def mainpage(request):

    return render(request, 'reco/main.html',{})


def result(request):

    print('**********')
    print(request.POST)
    print('**********')
    ingre = request.POST['ingredients[]']
    print(ingre)

    top7_reco = recommend(ingre)

    selected_3_choice = []
    selected_4_choice = []

    for id in top7_reco[:3]:
        selected_3_choice.append(Recipe_info.objects.get(recipe_id=id))
    print(selected_3_choice)
    for id in top7_reco[3:]:
        selected_4_choice.append(Recipe_info.objects.get(recipe_id=id))
    print(selected_4_choice)
    context = {'ingredients':ingre,'reco_3_recipe':selected_3_choice,'reco_4_recipe':selected_4_choice}

    return render(request,'reco/result.html',context)


def detail(request, recipe_id) :
    try :
        recipe_choice = get_object_or_404(Recipe_info, recipe_id = recipe_id)
    except :
        # 구현 필요 부분
        context = {'error_message' : "선택된 레시피가 없습니다."}
        return render(request, "reco/index.html", context)
    else :
        # ingredient-unit split
        recipe_choice.ingredients = recipe_choice.ingredients[:-1] # 마지막 "|" 삭제
        ingredients_list = recipe_choice.ingredients.split("|")

        ingredients = {}
        chknum = 0
        for idx, str in enumerate(ingredients_list) :
            if  idx % 2 == 0 :
                ingredients_str = ingredients_list[idx] + " " + ingredients_list[idx + 1]
                ingredients[chknum] = ingredients_str
                chknum += 1

        recipe_choice.ingredients = ingredients

        # recipe split
        recipe_choice.recipes = recipe_choice.recipes[:-1] # 마지막 "|" 삭제
        recipes_list = recipe_choice.recipes.split("|")
        recipes = {}
        for idx, str in enumerate(recipes_list) :
            recipes[idx] = str

        recipe_choice.recipes = recipes

        context = {"recipe_choice" : recipe_choice}
        return render(request, "reco/detail.html", context)

reco/templates/reco/detail.html
{% extends 'reco/base.html' %}
{% block content %}

<section class="step3 cid-sxfROPJLbm" id="step3-c">
    <div class="container">
        <h2 class="mbr-section-title pb-3 mbr-fonts-style align-center display-2">
            {{ recipe_choice.titles }}
        </h2>
        <h3 class="mbr-section-subtitle pb-5 mbr-fonts-style align-center display-5" style = "padding-bottom: 1rem!important;">
            {{ recipe_choice.comment }}
        </h3>
        <h3 class="mbr-section-subtitle pb-5 mbr-fonts-style align-center display-5">
            {{ recipe_choice.type }} | {{ recipe_choice.serves }} | {{ recipe_choice.cooking }}
        </h3>
        <div class="media-container-row">
            <div class="media-block" style="width: 49%;">
                <div class="mbr-figure">
                    <img src={{ recipe_choice.images }}>
                </div>
            </div>

            <div class="step-container">
              <div class="card">
                  <div class="step-element d-flex">
                    <div class="step-text-content">
                      <h3 class="mbr-step-title pb-3 mbr-fonts-style display-5">
                        Ingredients
                      </h3>
                      <div style = "display : flex;">
                        <ul class="ingredients" style = "padding: 30px; list-style: none; background: #f9f9f9;">
                          {% for idx, ingredient in recipe_choice.ingredients.items %}
                            {% if idx|divisibleby:2 %}
                              <li style = "margin-bottom: 10px; padding-bottom: 10px; border-bottom: 1px dashed #dedede;">
                                  {{ ingredient }}
                              </li>
                            {% endif %}
                          {% endfor%}
                        </ul>
                        <ul class="ingredients" style = "padding: 30px; list-style: none; background: #f9f9f9;">
                          {% for idx, ingredient in recipe_choice.ingredients.items %}
                            {% if not idx|divisibleby:2 %}
                            <li style = "margin-bottom: 10px; padding-bottom: 10px; border-bottom: 1px dashed #dedede;">
                                {{ ingredient }}
                            </li>
                            {% endif %}
                          {% endfor%}
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>



                <!-- {% for idx, ingredient in recipe_choice.ingredients.items %}
                  <div class="card">
                      <div class="step-element d-flex">
                          <div class="step-wrapper pr-3">
                              <div class="step d-flex align-items-center justify-content-center">
                                  {{ idx }}
                              </div>
                          </div>
                          <div class="step-text-content">
                              <h4 class="mbr-step-title pb-3 mbr-fonts-style display-5">

                              </h4>
                              <p class="mbr-step-text mbr-fonts-style display-7">
                                {{ ingredient }}
                              </p>
                          </div>
                      </div>
                  </div>
                {% endfor %} -->
              </div>
            </div>
        </div>
</section>

<section class="timeline1 cid-sxfU72tGuV" id="timeline1-h">
    <div class="container align-center">
        <h2 class="mbr-section-title pb-5 mbr-fonts-style display-2">
            Recipe
        </h2>

        <div class="container timelines-container" mbri-timelines="">
          {% for idx, recipe in recipe_choice.recipes.items %}
              <!--1-->
              <!-- <div class="row timeline-element separline">
                <div class="timeline-date-panel col-xs-12 col-md-6  align-left">
                  <div class="time-line-date-content">
                    <p class="mbr-timeline-date mbr-fonts-style display-5">
                      {{ idx|add:1 }}
                    </p>
                  </div>
                </div>
                <span class="iconBackground"></span>
                <div class="col-xs-12 col-md-6 align-right">
                  <div class="timeline-text-content">
                    <h4 class="mbr-timeline-title pb-3 mbr-fonts-style display-5">
                      {{ recipe }}
                    </h4>
                    <p class="mbr-timeline-text mbr-fonts-style display-7">
                      {{ recipe }}
                    </p>
                  </div>
                </div>
              </div> -->
              <!--2-->
              <div class="row timeline-element  separline">
                <div class="timeline-date-panel col-xs-12 col-md-6 align-right">
                  <div class="time-line-date-content">
                    <p class="mbr-timeline-date mbr-fonts-style display-5">
                      {{ idx|add:1 }}
                    </p>
                  </div>
                </div>
                <span class="iconBackground"></span>
                <div class="col-xs-12 col-md-6 align-left ">
                  <div class="timeline-text-content">
                    <!-- <h4 class="mbr-timeline-title pb-3 mbr-fonts-style display-5">
                      {{ recipe }}
                    </h4> -->
                    <p class="mbr-timeline-text mbr-fonts-style display-7">
                      {{ recipe }}
                    </p>
                  </div>
                </div>
              </div>
          {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

reco/templates/reco/index.html
<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.12.4, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.12.4, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <!-- 아이콘 설정   -->
  <link rel="shortcut icon" href="/static/reco/assets/images/logo2.png" type="image/x-icon">
  <meta name="description" content="">
  
  
  <title>Home</title>
  <link rel="stylesheet" href="/static/reco/assets/web/assets/mobirise-icons/mobirise-icons.css">
  <link rel="stylesheet" href="/static/reco/assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/reco/assets/bootstrap/css/bootstrap-grid.min.css">
  <link rel="stylesheet" href="/static/reco/assets/bootstrap/css/bootstrap-reboot.min.css">
  <link rel="stylesheet" href="/static/reco/assets/socicon/css/styles.css">
  <link rel="stylesheet" href="/static/reco/assets/dropdown/css/style.css">
  <link rel="stylesheet" href="/static/reco/assets/tether/tether.min.css">
  <link rel="stylesheet" href="/static/reco/assets/theme/css/style.css">
  <link rel="stylesheet" href="/static/reco/assets/gallery/style.css">
  <link rel="preload" as="style" href="/static/reco/assets/mobirise/css/mbr-additional.css"><link rel="stylesheet" href="/static/reco/assets/mobirise/css/mbr-additional.css" type="text/css">

</head>
<body>
<section class="features3 cid-sxfRolSOgY" id="features3-b">

    <div class="container">
        <div class="media-container-row">
            <div class="card p-3 col-12 col-md-6 col-lg-4">
                <div class="card-wrapper">
                    <div class="card-img">
                        <img src="https://recipe1.ezmember.co.kr/cache/recipe/2021/05/12/941ddb1f27e57d27ca07dcd77c102e5a1.jpg">
                    </div>
                    <div class="card-box">
                        <h4 class="card-title mbr-fonts-style display-7">
                            No Coding
                        </h4>
                        <p class="mbr-text mbr-fonts-style display-7">
                            Mobirise is an easy website builder - just drop site elements to your page, add content and style it to look the way you like.
                        </p>
                    </div>
                    <div class="mbr-section-btn text-center">
                        <a href="https://mobirise.co" class="btn btn-primary display-4">
                            Learn More
                        </a>
                    </div>
                </div>
            </div>

            <div class="card p-3 col-12 col-md-6 col-lg-4">
                <div class="card-wrapper">
                    <div class="card-img">
                        <img src="/static/reco/assets/images/background2.jpg" alt="Mobirise">
                    </div>
                    <div class="card-box">
                        <h4 class="card-title mbr-fonts-style display-7">
                            Mobile Friendly
                        </h4>
                        <p class="mbr-text mbr-fonts-style display-7">
                            All sites you make with Mobirise are mobile-friendly. You don't have to create a special mobile version of your site.
                        </p>
                    </div>
                    <div class="mbr-section-btn text-center">
                        <a href="https://mobirise.co" class="btn btn-primary display-4">
                            Learn More
                        </a>
                    </div>
                </div>
            </div>

            <div class="card p-3 col-12 col-md-6 col-lg-4">
                <div class="card-wrapper">
                    <div class="card-img">
                        <img src="/static/reco/assets/images/background3.jpg" alt="Mobirise">
                    </div>
                    <div class="card-box">
                        <h4 class="card-title mbr-fonts-style display-7">
                            Unique Styles
                        </h4>
                        <p class="mbr-text mbr-fonts-style display-7">
                            Mobirise offers many site blocks in several themes, and though these blocks are pre-made, they are flexible.
                        </p>
                    </div>
                    <div class="mbr-section-btn text-center">
                        <a href="https://mobirise.co" class="btn btn-primary display-4">
                            Learn More
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



  <script src="/static/reco/assets/web/assets/jquery/jquery.min.js"></script>
  <script src="/static/reco/assets/popper/popper.min.js"></script>
  <script src="/static/reco/assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="/static/reco/assets/smoothscroll/smooth-scroll.js"></script>
  <script src="/static/reco/assets/dropdown/js/nav-dropdown.js"></script>
  <script src="/static/reco/assets/dropdown/js/navbar-dropdown.js"></script>
  <script src="/static/reco/assets/touchswipe/jquery.touch-swipe.min.js"></script>
  <script src="/static/reco/assets/masonry/masonry.pkgd.min.js"></script>
  <script src="/static/reco/assets/imagesloaded/imagesloaded.pkgd.min.js"></script>
  <script src="/static/reco/assets/bootstrapcarouselswipe/bootstrap-carousel-swipe.js"></script>
  <script src="/static/reco/assets/tether/tether.min.js"></script>
  <script src="/static/reco/assets/vimeoplayer/jquery.mb.vimeo_player.js"></script>
  <script src="/static/reco/assets/theme/js/script.js"></script>
  <script src="/static/reco/assets/slidervideo/script.js"></script>
  <script src="/static/reco/assets/gallery/player.min.js"></script>
  <script src="/static/reco/assets/gallery/script.js"></script>
  <script src="/static/reco/assets/formoid/formoid.min.js"></script>
  
  
</body>
</html>

reco/templates/reco/main.html
{% extends 'reco/base.html' %}
{% block content %}
 section 1 : video
<section class="header7 cid-sxfQ0aMh1o" id="header7-1" style="padding-top: 150px;">

    <div class="container">
        <div class="media-container-row">

            <div class="media-content align-right">
                <h1 class="mbr-section-title mbr-white pb-3 mbr-fonts-style display-1">
                    RECO 시연 영상
                </h1>
                <div class="mbr-section-text mbr-white pb-3">
                    <p class="mbr-text mbr-fonts-style display-5">
                        RECO는 재료에 따라 퍼스널 레시피를 추천해드리는 서비스입니다. 지금 RECO와 함께 냉장고 속 잠자는 재료를 깨워보세요!
                    </p>
                </div>
            </div>

            <div class="mbr-figure" style="width: 100%;">
                <iframe class="mbr-embedded-video" src="https://www.youtube.com/embed/uNCr7NdOJgw?rel=0&amp;amp;showinfo=0&amp;autoplay=0&amp;loop=0" width="1280" height="720" frameborder="0" allowfullscreen>
                </iframe>
            </div>

        </div>
    </div>
</section>

<!-- section 2 : step -->
<section class="step2 cid-sxfQXUQcjD" id="step2-4" style="padding-top: 70px;">

    <div class="container">
        <h2 class="mbr-section-title pb-3 mbr-fonts-style align-center display-2">
            Steps
        </h2>
        <h3 class="mbr-section-subtitle pb-5 mbr-fonts-style align-center display-5">
            내가 가지고 있는 재료를 입력하면 레시피를 추천해드립니다
        </h3>
        <div class="step-container row justify-content-center">
            <div class="card col-12 col-md-4 separline">
                <div class="step-element">
                    <div class="step-wrapper pb-3">
                        <h3 class="step d-flex align-items-center justify-content-center m-auto">
                            1
                        </h3>
                    </div>
                    <div class="step-text-content align-center">
                        <h4 class="mbr-step-title pb-3 mbr-fonts-style display-5">Ingredient
                        </h4>
                        <p class="mbr-step-text mbr-fonts-style display-7">
                            냉장고에 있는 재료 2가지 이상을 입력하세요</p>
                    </div>
                </div>
            </div>

            <div class="card col-12 separline col-md-4">
                <div class="step-element">
                    <div class="step-wrapper pb-3">
                        <h3 class="step d-flex align-items-center justify-content-center m-auto">
                            2
                        </h3>
                    </div>
                    <div class="step-text-content align-center">
                        <h4 class="mbr-step-title pb-3 mbr-fonts-style display-5">Menu</h4>
                        <p class="mbr-step-text mbr-fonts-style display-7">
                            추천된 메뉴 중 먹고 싶은 음식을 선택해주세요</p>
                    </div>
                </div>
            </div>

            <div class="card col-md-4 col-12 separline last-child">
                <div class="step-element">
                    <div class="step-wrapper pb-3">
                        <h3 class="step d-flex align-items-center justify-content-center m-auto">
                            3
                        </h3>
                    </div>
                    <div class="step-text-content align-center">
                        <h4 class="mbr-step-title pb-3 mbr-fonts-style display-5">Recipe
                        </h4>
                        <p class="mbr-step-text mbr-fonts-style display-7">
                            소개된 레시피를 따라 음식을 만들면 됩니다</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

 section 3 : search
<section class="mbr-section form3 cid-sxfTz6EAq9" id="form3-g" style="padding-top: 0;">
    <div class="container">
        <div class="row justify-content-center">
            <div class="title col-12 col-lg-8">
                <h2 class="align-center pb-2 mbr-fonts-style display-2">
                    가지고 있는 재료를 입력하세요
                </h2>
                <h3 class="mbr-section-subtitle align-center pb-5 mbr-light mbr-fonts-style display-5">
                    최소 2가지 이상
                </h3>
            </div>
        </div>
        <div class="row py-2 justify-content-center">-->
            <form action="{% url 'reco:result' %}" method="POST">
                    {% csrf_token %}
                    <div class="dragArea row">
                        <div class="form-group col">
                            <input type="text" name="ingredients" required="required" class="form-control display-7" id="email-form3-g">
                            <input type="hidden" name="ingredients[]" id="ingredients_list" values="">
                        </div>
                        <div class="col-auto input-group-btn">
                            <button type="button" class="btnAdd">+재료추가</button>
                            <button type="submit" onclick="getlist()">확인</button>
                        </div>
                    </div>
                </form>
            </div>
    </div>
</section>
<script src="/static/reco/assets/web/assets/jquery/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready ( function() {
        $('.btnAdd').click ( function() {
            $('.form-group').append (
                '<input type="type" name="ingredients" required="required" class="form-control display-7" id="email-form3-g">\
                <button type="button" class="btnRemove">-</button><br>'
                );
                $('.btnRemove').on('click',function() {
                    $(this).prev().remove();
                    $(this).next().remove();
                    $(this).remove();
                });
            });
        });
</script>
<script type="text/javascript">
    function getlist() {
        var list = new Array();
        $("input[name=ingredients]").each( function(index, item) {
            list.push($(item).val());
        });
        $("#ingredients_list").val(list);
    }
</script>
{% endblock %}

reco/templates/reco/result.html
<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.12.4, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.12.4, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <!-- 아이콘 설정   -->
  <link rel="shortcut icon" href="/static/reco/assets/images/logo2.png" type="image/x-icon">
  <meta name="description" content="">

  <title>Home</title>
  <link rel="stylesheet" href="/static/reco/assets/web/assets/mobirise-icons/mobirise-icons.css">
  <link rel="stylesheet" href="/static/reco/assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/reco/assets/bootstrap/css/bootstrap-grid.min.css">
  <link rel="stylesheet" href="/static/reco/assets/bootstrap/css/bootstrap-reboot.min.css">
  <link rel="stylesheet" href="/static/reco/assets/socicon/css/styles.css">
  <link rel="stylesheet" href="/static/reco/assets/dropdown/css/style.css">
  <link rel="stylesheet" href="/static/reco/assets/tether/tether.min.css">
  <link rel="stylesheet" href="/static/reco/assets/theme/css/style.css">
  <link rel="stylesheet" href="/static/reco/assets/gallery/style.css">
  <link rel="preload" as="style" href="/static/reco/assets/mobirise/css/mbr-additional.css"><link rel="stylesheet" href="/static/reco/assets/mobirise/css/mbr-additional.css" type="text/css">
        <link href="css/font-awesome.min.css" rel="stylesheet">

    <!-- CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/styles.min.css" rel="stylesheet">
    <link href="css/select2.min.css" rel="stylesheet">

</head>
<body>
<section class="features3 cid-sxfRolSOgY" id="features3-b">
    {% if reco_3_recipe %}
    <h3>&ensp;&ensp; &ensp;  {{ ingredients }} 검색 결과..</h3>
    <div class="container">
        <div class="media-container-row">
            {% for reco in reco_3_recipe %}
            <div class="card p-9 col-12 col-md-6 col-lg-4">
                <div class="card-wrapper">
                    <div class="card-img" >
                        <img src="{{ reco.images }}" alt="Mobirise">
                    </div>
                    <div class="card-box">
                        <h4 class="card-title mbr-fonts-style display-7">
                            {{ reco.titles }}
                        </h4>
                        <p class="mbr-text mbr-fonts-style display-7">
                            {{ reco.comment }}
                        </p>
                    </div>
                    <div class="mbr-section-btn text-center">
                        <a href="{% url 'reco:detail' reco.recipe_id %}" class="btn btn-primary display-4">
                            Read More
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
</section>
<section class="mbr-gallery mbr-slider-carousel cid-sxfTwgWOXf" id="gallery2-f">

    <div class="container">
        <div><!-- Filter -->
            <div class="mbr-gallery-row">
                {% for reco in reco_4_recipe %}
                <div class="mbr-gallery-layout-default">
                    <div>
                        <div class="mbr-gallery-item mbr-gallery-item--p2" data-video-url="false">
                            <div href="{% url 'reco:detail' reco.recipe_id %}" data-toggle="modal">
                                <img src="{{ reco.images }}" width="150px" height="150px">
                                <span class="icon-focus">

                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div><!-- Lightbox -->
    </div>
</div>
</section>
  <script src="/static/reco/assets/web/assets/jquery/jquery.min.js"></script>
  <script src="/static/reco/assets/popper/popper.min.js"></script>
  <script src="/static/reco/assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="/static/reco/assets/smoothscroll/smooth-scroll.js"></script>
  <script src="/static/reco/assets/dropdown/js/nav-dropdown.js"></script>
  <script src="/static/reco/assets/dropdown/js/navbar-dropdown.js"></script>
  <script src="/static/reco/assets/touchswipe/jquery.touch-swipe.min.js"></script>
  <script src="/static/reco/assets/masonry/masonry.pkgd.min.js"></script>
  <script src="/static/reco/assets/imagesloaded/imagesloaded.pkgd.min.js"></script>
  <script src="/static/reco/assets/bootstrapcarouselswipe/bootstrap-carousel-swipe.js"></script>
  <script src="/static/reco/assets/tether/tether.min.js"></script>
  <script src="/static/reco/assets/vimeoplayer/jquery.mb.vimeo_player.js"></script>
  <script src="/static/reco/assets/theme/js/script.js"></script>
  <script src="/static/reco/assets/slidervideo/script.js"></script>
  <script src="/static/reco/assets/gallery/player.min.js"></script>
  <script src="/static/reco/assets/gallery/script.js"></script>
  <script src="/static/reco/assets/formoid/formoid.min.js"></script>
</body>
</html>

reco/templates/reco/sample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="search">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Browse Recipes</h2>
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label>Choose category</label>
                                <select class="js-search-category form-control" name="category" data-placeholder="Choose Category">
                                    <option value="1">All</option>
                                    <option value="2">Breakfast</option>
                                    <option value="3">Lunch</option>
                                    <option value="4">Beverages</option>
                                    <option value="5">Appetizers</option>
                                    <option value="6">Soups</option>
                                    <option value="7">Salads</option>
                                    <option value="8">Beef</option>
                                    <option value="9">Poultry</option>
                                    <option value="10">Pork</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Select one or more ingredients that should be included in recipe</label>
                                <select class="js-search-ingredients form-control" name="ingredients[]" multiple="multiple" data-placeholder="Included Ingredients">
                                    <option value="sugar">sugar</option>
                                    <option value="wheat-flour">wheat flour</option>
                                    <option value="baking-powder">baking powder</option>
                                  </select>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label>Recipe needs to have</label>
                                <select class="js-search-category2 form-control" name="category" data-placeholder="Choose Category">
                                    <option value="1">All of selected ingredients </option>
                                    <option value="2">Any of selected ingredients</option>
                                  </select>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="form-group">
                                <input type="email" class="form-control" placeholder="Search by Keyword">
                                <button type="submit" class="btn">Search Recipes</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>